/// <reference types="vitest/config" />
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import wasm from "vite-plugin-wasm";

// Dev mode: vite serves the frontend with HMR and proxies API calls to the
// rust backend (`cargo run -- serve`). Production: `vite build` output is
// served by the backend itself.
export default defineConfig({
  // wasm(): the shared change fold (crates/nit-wasm) ships as a wasm-bindgen
  // bundler module; this plugin instantiates its `.wasm` import in dev, build,
  // and vitest alike (src/wasm is generated by `nix run .#gen-wasm`).
  plugins: [react(), wasm()],
  server: {
    proxy: {
      "/api": "http://127.0.0.1:8877",
    },
  },
  // Vitest (`npm test`): jsdom so component tests have a DOM; VITE_MOCK so
  // client.ts answers from the contract-true fixtures — the same canned
  // data the screenshot harness renders.
  test: {
    environment: "jsdom",
    env: { VITE_MOCK: "1" },
  },
});
